apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-platform-dev
  labels:
    environment: dev
    managed-by: argocd

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: kubernetes-platform-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: kubernetes-platform-dev
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi