apiVersion: v1
kind: Service

metadata:
  name: kubernetes-platform

spec:

  type: {{ .Values.service.type }}

  selector:
    app: kubernetes-platform

  ports:

    - name: http

      port: {{ .Values.service.port }}

      targetPort: http