apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: kubernetes-platform
  namespace: argocd

spec:
  description: Argo CD project for the random application

  sourceRepos:
    - https://github.com/SantiagoLemoMayoral/kubernetes-platform.git

  destinations:
    - namespace: kubernetes-platform-dev
      server: https://kubernetes.default.svc

    - namespace: kubernetes-platform-staging
      server: https://kubernetes.default.svc

    - namespace: kubernetes-platform-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"